{% set version = "1.5" %}

package:
  name: openmvg
  version: {{ version }}

source:
  - url: https://github.com/openMVG/openMVG/archive/v{{ version }}.tar.gz
    fn: openmvg-{{ version }}.tar.gz
    sha256: 4f89edb0d4568aeb817fcbd3c761e8bfc92c1597b97c4b5482cfe9989f40ab97
    patches: 
      - fixcmake.patch

build:
  number: 1000
  skip: true # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - m2-patch # [win]
  
  host:
    - cereal
    - ceres-solver
    - clp
    - coinutils
    - eigen 3.3.7
    - flann
    - lemon
    - libjpeg-turbo
    - libpng
    - libtiff 4.0.10
    - osi
    - zlib

  run:
    - cereal
    - ceres-solver
    - clp
    - coinutils
    - eigen 3.3.7
    - flann
    - lemon
    - libpng
    - libtiff 4.0.10
    - osi
    - zlib

about:
  home: https://github.com/openMVG/openMVG
  license: MPL2
  license_file: LICENSE
  summary: open Multiple View Geometry library. Basis for 3D computer vision and Structure from Motion.

extra:
  recipe-maintainers:
    - saedrna
