{% set version = "2.7.2" %}

package:
  name: catch2
  version: {{ version }}

source:
  - url: https://github.com/catchorg/Catch2/archive/v{{ version }}.tar.gz
    fn: catch2-{{ version }}.tar.gz
    sha256: 9f4116da13d8402b5145f95ab91ae0173cd27b804152d3bb2d4f9b6e64852af7

build:
  number: 1000

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    


about:
  home: https://github.com/catchorg/Catch2
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: A modern, C++-native, header-only, test framework for unit-tests.

extra:
  recipe-maintainers:
    - saedrna
