channels:
  - saedrna
  - conda-forge
  - intel
  - defaults
dependencies:
  - blas 2.5 openblas
  - boost-cpp 1.69.0
  - capstone 
  - cereal
  - ceres-solver
  - cgal-cpp
  - clp 
  - coinutils
  - eigen 3.3.7
  - flann 
  - geographiclib 1.49
  - glew
  - glfw
  - glog 0.4.0
  - ipp-include 
  - ipp-static
  - khronos-opencl-icd-loader
  - laszip 
  - libgdal
  - libtiff 4.0.10
  - open3d
  - openblas 0.3.5
  - opencv 4.1.0
  - openmvg
  - openscenegraph 3.4.1
  - osi
  - pcl 1.9.1
  - qhull 2015.2
  - qt3d 5.12.3
  - qt5-base 5.12.3
  - qt5-charts 5.12.3
  - qt5-declarative 5.12.3
  - qt5-graphicaleffects 5.12.3
  - qt5-imageformats 5.12.3
  - qt5-quickcontrols2 5.12.3
  - qt5-svg 5.12.3
  - qt5-tools 5.12.3
  - qt5-winextras 5.12.3
  - suitesparse 5.1.2
  - tbb 
  - viennacl 
  - zlib 1.2.11
