{% set version = "2.11.1" %}

package:
  name: coinutils
  version: {{ version }}

source:
  - url: https://github.com/coin-or/CoinUtils/archive/releases/2.11.1.tar.gz
    fn: {{ version }}.tar.gz
    sha256: 4098a8c3f5ea8663c3955996493d2143979d1c226fed2eb8b85d210343c76e84

build:
  number: 0
  skip: true # [not win]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    

about:
  home: https://github.com/coin-or/CoinUtils
  license: Eclipse Public License (EPL)
  license_file: LICENSE
  summary: COIN-OR Utilities.

extra:
  recipe-maintainers:
    - saedrna
