{% set version = "0.4.0" %}

package:
  name: glog
  version: {{ version }}

source:
  fn: glog-{{ version }}.tar.gz
  url: https://github.com/google/glog/archive/v{{ version }}.tar.gz
  sha256: f28359aeba12f30d73d9e4711ef356dc842886968112162bc73002645139c39c


build:
  number: 1000

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gflags
  
  run:
    - gflags

about:
  home: https://github.com/google/glog
  license: BSD 3-Clause
  license_file: COPYING
  summary: C++ implementation of the Google logging module.

extra:
  recipe-maintainers:
    - saedrna
