{% set version = "4.14" %}

package:
  name: cgal-cpp
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-{{ version }}/CGAL-{{ version }}.zip
  sha256: b5d149726266f5f87d84f896aec672e07846ebf8b2ba2a33e696feaa2e250ef3

build:
  number: 0
  # mpfr only supports vc14
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - boost-cpp 1.69.0
    - mpfr
    - eigen 3.3.7 *
  run:
    - boost-cpp 1.69.0
    - mpfr
    - eigen 3.3.7 *

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - saedrna
