{% set version = "5.1.2" %}
{% set commit = "9fff863f2a60fc18869c330dcdf5945e2f8930df" %}

{% set variant = "openblas" %}

package:
  name: suitesparse
  version: {{ version }}

source:
  fn: SuiteSparse-{{ version }}.tar.gz
  url: https://github.com/jlblancoc/suitesparse-metis-for-windows/archive/{{ commit }}.tar.gz
  sha256: ff150a85b26e9c6a87a56770d5e26b08fd1208b35da8c28d37a436142a65e2b7 
  patches:
    - 1-gh_56.patch  # [win]
    - 2-linux-fix-rt.patch # [linux]
    
build:
  skip: true  # [win32]
  skip: True  # [win and vc<14]
  number: 1000

requirements:
  build:
    - cmake
    - ninja
    - m2-patch # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - blas * openblas

  run:
    - blas * openblas

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: LGPL v2 (AMD, BTF, etc), BSD 3-clause (UFget), GPL v2 (UMFPACK, RBIO, SPQR, GPUQRENGINE), Apache 2.0 (Metis)
  summary: A suite of sparse matrix algorithms

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
    - saedrna
