{% set version = "0.108.3" %}

package:
  name: osi
  version: {{ version }}

source:
  - url: https://github.com/coin-or/Osi/archive/releases/0.108.3.tar.gz
    fn: {{ version }}.tar.gz
    sha256: db6384e89d301ad62ff1acc46777a8fb89668d4266d4b2ddfb9f454edcdc8c77

build:
  number: 1000
  skip: true # [not win]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - coinutils 2.11.1
  run:
    - coinutils 2.11.1

about:
  home: https://github.com/coin-or/Osi
  license: Eclipse Public License (EPL)
  license_file: LICENSE
  summary: Open Solver Interface.

extra:
  recipe-maintainers:
    - saedrna
