{% set version = "1.7.5" %}

package:
  name: geogram
  version: {{ version }}

source:
  - url: https://github.com/alicevision/geogram/archive/v{{ version }}.tar.gz
    fn: geogram-{{ version }}.tar.gz
    sha256: 5bc3eb0bed27feed0c4f2406ca85328e65013a6a7881c50bd41fb53384306ef6
  # - url: https://github.com/alicevision/geogram/archive/v{{ version }}.zip # [win]
  #   fn: geogram-{{ version }}.zip # [win]
  #   sha256: d69fcf92d2671e1881f2bdec3f9595ce818c554e7375c1397d699a93069e1991 # [win]
build:
  number: 1001

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  
  host:
    - libblas
    - libcblas
    - liblapack  
  run:
    - libblas
    - libcblas
    - liblapack

about:
  home: http://alice.loria.fr/index.php/software/4-library/75-geogram.html
  license: 3-clauses BSD License
  summary: Geogram is a programming library of geometric algorithms. 

extra:
  recipe-maintainers:
    - saedrna
