{% set version = "0.6.0" %}

package:
  name: open3d
  version: {{ version }}

source:
  - url: https://github.com/intel-isl/Open3D/archive/v{{ version }}.tar.gz
    fn: open3d-{{ version }}.tar.gz
    sha256: c415c3213e732c6ccc135e5216a79e7d81e81017813108aa391e5d7f5c60bbc3
    patches:
      - fix-cmake.patch

build:
  number: 0


requirements:
  build:
    - cmake
    - ninja
    - m2-patch # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - eigen 3.3.7
    - flann
    - glew
    - glfw
    - libpng
    - zlib
    - libjpeg-turbo
    - jsoncpp

  run:
    - eigen 3.3.7
    - jsoncpp
    - flann
    - glew
    - glfw

about:
  home: http://www.open3d.org
  license: MIT
  summary: Open3D, A Modern Library for 3D Data Processing
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saedrna