{% set version = "4.1.0" %}

package:
  name: assimp
  version: {{ version }}

source:
  - url: https://github.com/assimp/assimp/archive/v{{ version }}.tar.gz
    fn: assimp-{{ version }}.tar.gz
    sha256: 3520b1e9793b93a2ca3b797199e16f40d61762617e072f2d525fad70f9678a71

build:
  number: 1000

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
  run: 
    - zlib

about:
  home: https://github.com/assimp/assimp
  license: 3-clause BSD
  license_file: LICENSE
  summary: A library to import and export various 3d-model-formats including scene-post-processing to generate missing render data.

extra:
  recipe-maintainers:
    - saedrna
