{% set version = "5.7.0" %}

package:
  name: qt5charts
  version: {{ version }}

source:
  - url: http://download.qt.io/development_releases/qt/5.7/5.7.0-rc/submodules/qtcharts-opensource-src-5.7.0-rc.zip
    fn: qt5charts-{{ version }}.zip
    sha256: be16d4c16b8cee8127a47a84adc9c30570ab14f0010adf6752935cf84c77b644

build:
  number: 0

requirements:
  build:
    - jom # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  
  host:
    - qt 5.6.2

  run:
    - qt 5.6.2


about:
  home: https://github.com/qt/qtcharts
  license: GPL-3.0
  license_file: README
  summary: QtCharts module

extra:
  recipe-maintainers:
    - saedrna
