{% set version = "3.6.2" %}
{% set git_branch = "master" %}
{% set build_number = "0" %}

package:
  name: isis3
  version: {{ version }}

source:
  git_url: 'https://github.com/saedrna/ISIS3.git'
  git_branch: {{ git_branch }}

build:
  number: {{ build_number }}

# Shotgun strat on requirements until we can narrow them down
requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
  host:  
    - armadillo
    - blas 2.5 openblas
    - bullet
    - bz2file
    - bzip2
    - ceres-solver
    - cspice
    - eigen
    - embree
    - geos==3.5.1
    - geotiff
    - gmm
    - gmp
    - gsl
    - hdf5
    - jama
    - jpeg
    - krb5
    - libgdal
    - libpng
    - libprotobuf
    - libtiff
    - libxml2
    - mesalib
    - mysql
    - mysql-connector-c
    - nanoflann
    - nn
    - openblas
    - opencv
    - pcl
    - protobuf
    - python>=3.6
    - qhull
    - qt5-base                      # [win]
    - qt5-declarative               # [win]
    - qt5-imageformats              # [win]
    - qt5-multimedia                # [win]
    - qt5-quickcontrols             # [win]
    - qt5-quickcontrols2            # [win]
    - qt5-script                    # [win]
    - qt5-svg                       # [win]
    - qt5-webchannel                # [win]
    - qt5-xmlpatterns               # [win]
    - qwt
    - qt                            # [not win]
    - suitesparse
    - superlu
    - tnt
    - x264
    - xerces-c
    - xorg-kbproto
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxi
    - zlib
  run:
    - armadillo
    - blas 2.5 openblas
    - bullet
    - bz2file
    - bzip2
    - ceres-solver
    - cspice
    - eigen
    - embree
    - geos==3.5.1
    - geotiff
    - gmm
    - gmp
    - gsl
    - hdf5
    - jama
    - jpeg
    - krb5
    - libgdal
    - libpng
    - libprotobuf
    - libtiff
    - libxml2
    - mesalib
    - mysql
    - mysql-connector-c
    - nanoflann
    - nn
    - openblas
    - opencv
    - pcl
    - protobuf
    - python>=3.6
    - qhull
    - qt5-base
    - qt5-declarative
    - qt5-imageformats
    - qt5-multimedia
    - qt5-quickcontrols
    - qt5-quickcontrols2
    - qt5-script
    - qt5-svg
    - qt5-webchannel
    - qt5-xmlpatterns
    - qwt
    - suitesparse
    - superlu
    - tnt
    - x264
    - xerces-c
    - xorg-kbproto
    - xorg-libice
    - xorg-libsm
    - xorg-libx11
    - xorg-libxi
    - zlib

extra:
  recipe-maintainers:
    - saedrna
