{% set version = "0.8.4" %}

package:
  name: xkbcommon
  version: {{ version }}

source:
  url: https://github.com/xkbcommon/libxkbcommon/archive/xkbcommon-{{ version }}.tar.gz
  sha256: 1299b47558188017047354995f5882d43c2c8a60367df553319dcecebadb73e1d


build:
  number: 1000
  skip: True # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson  
    - ninja

  host:
  run:

about:
  home: https://github.com/xkbcommon/libxkbcommon
  license: MIT
  license_file: LICENSE
  summary: 'keymap handling library for toolkits and window systems'

extra:
   recipe-maintainers:
    - saedrna
