{% set version = "4.2.0" %}
{% set blas_variant = "openblas" %}

package:
  name: opencv
  version: {{ version }}

source:
  - url: https://github.com/opencv/opencv/archive/{{ version }}.tar.gz
    fn: opencv-{{ version }}.tar.gz
    sha256: 9ccb2192d7e8c03c58fee07051364d94ed7599363f3b0dce1c5e6cc11c1bb0ec
  - url: https://github.com/opencv/opencv_contrib/archive/{{ version }}.tar.gz
    fn: opencv_contrib-{{ version }}.tar.gz
    sha256: 8a6b5661611d89baa59a26eb7ccf4abb3e55d73f99bb52d8f7c32265c8a43020
    folder: opencv_contrib

build:
  number: 1000
  # Python2.7 support dropped: https://github.com/opencv/opencv/issues/8481
  # skip: true  # [win and py27]

requirements:
  build:
    # Required to find ffpmeg
    - pkg-config                     # [not win]
    # - m2-patch                       # [win]
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
  host:
    - eigen 3.3.7
    - ffmpeg 4.1.*                   # [not win]
    - khronos-opencl-icd-loader      # [not linux]
    - libjpeg-turbo
    - libpng
    - libtiff
    - ocl-icd                        # [linux]
    - zlib
  run:
    - eigen 3.3.7
    - ffmpeg 4.1.*                   # [not win]
    - khronos-opencl-icd-loader      # [not linux]
    - libpng
    - libtiff
    - ocl-icd                        # [linux]
    - zlib

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: Computer vision and machine learning software library.
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saedrna