{% set version = "9.200.4" %}

package:
    name: armadillo
    version: {{ version }}

source:
    fn: armadillo-{{ version }}.tar.xz
    url: http://sourceforge.net/projects/arma/files/armadillo-{{ version }}.tar.xz
    sha256: 10d1cc38503624bf1ad8c55c0d53b4feb80f04fcb3f5c3e6a69ba95d00f17966
    patches:
        - CMakeLists.patch  # [unix]

build:
  number: 1205
  skip: true  # [win and vc<14]
  skip: true # [linux or osx]
  run_exports:
    - {{ pin_subpackage('armadillo', min_pin='x.x', max_pin='x') }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # optional items below here
    - blas * openblas
  run:
    - blas * openblas

about:
    home: http://arma.sourceforge.net
    license: Apache 2.0
    license_file: LICENSE.txt
    summary: Armadillo C++ linear algebra library

extra:
    recipe-maintainers:
      - grlee77
      - dirmeier
      - marcelotrevisani
      - saedrna

