{% set version = "1.50" %}

package:
  name: geographiclib
  version: {{ version }}

source:
  - url: https://nchc.dl.sourceforge.net/project/geographiclib/distrib/GeographicLib-{{ version }}.tar.gz
    fn: geographiclib-{{ version }}.tar.gz
    sha256: 2ac8888094d21ba48adb433c4bb569937497b39733e96c080b5ce278e2587622

build:
  number: 1000

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  
  host:


about:
  home: https://geographiclib.sourceforge.io/
  license: MIT
  license_file: LICENSE.txt
  summary: GeographicLib is a small set of C++ classes for performing conversions between geographic, UTM, UPS, MGRS, geocentric, and local cartesian coordinates, for gravity (e.g., EGM2008), geoid height, and geomagnetic field (e.g., WMM2010) calculations, and for solving geodesic problems. 

extra:
  recipe-maintainers:
    - saedrna
