{% set version = "2.2.2" %}

package:
  name: gflags
  version: {{ version }}

source:
  fn: gflags-{{ version }}.tar.gz
  url: https://github.com/gflags/gflags/archive/v{{ version }}.tar.gz
  sha1: 4d42470afb7236fb0cf90f8bbb0cec588073c17c


build:
  number: 1002

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  

about:
  home: https://github.com/gflags/gflags
  license: BSD 3-Clause
  license_file: COPYING.txt
  summary: A C++ library that implements commandline flags processing.

extra:
  recipe-maintainers:
    - jakirkham
    - wesm
    - xhochy
    - saedrna
