{% set version = "1.9.1" %}

package:
    name: flann
    version: {{ version }}

source:
    fn: flann-{{ version }}.tar.gz
    url: https://github.com/mariusmuja/flann/archive/{{ version }}.tar.gz
    sha256: b23b5f4e71139faa3bcb39e6bbcc76967fbaf308c4ee9d4f5bfbeceaa76cc5d3
    patches: # [linux]
        # CMake 3.11 breaks FLANN's existing src/cpp/CMakeLists.txt. See
        # https://github.com/mariusmuja/flann/issues/369 for more information.
        - src-cpp-fix-cmake-3.11-build.patch

build:
    number: 1006

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
    host:

about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD 3-Clause
    license_file: COPYING
    summary: "The Fast Library for Approximate Nearest Neighbors"

extra:
  recipe-maintainers:
    - jakevdp
    - jakirkham
    - dougalsutherland
    - saedrna
