{% set version = "1.2.2" %}

package:
  name: cereal
  version: {{ version }}

source:
  - url: https://github.com/USCiLab/cereal/archive/v{{ version }}.tar.gz
    fn: cereal-{{ version }}.tar.gz
    sha256: 1921f26d2e1daf9132da3c432e2fd02093ecaedf846e65d7679ddf868c7289c4

build:
  number: 1000

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    


about:
  home: https://github.com/USCiLab/cereal
  license: BSD license
  license_file: LICENSE
  summary: A C++11 library for serialization.

extra:
  recipe-maintainers:
    - saedrna
